NAME: 'orgmim'

MODEL:
  pre_train: False
  continue_train: False
  pretrain_path: None
  continue_path: None
  pool_op_kernel_sizes: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 1, 1]]
  conv_kernel_sizes: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  depth: [1, 1, 1, 1, 1, 1]
  dims: [32, 64, 128, 256, 512, 512]
  img_size: 128
  patch_size: 16


TRAIN:
  cache_path: './caches/'
  save_path: './models/'
  display_freq: 100
  total_iters: 400000
  warmup_iters: 0
  base_lr: 0.0001
  end_lr: 0.0001
  save_freq: 2000
  valid_freq: 1000
  decay_iters: 200000
  weight_decay: ~
  power: 1.5
  batch_size: 4
  num_workers: 16
  if_cuda: True
  random_seed: 666  
  loss_forward: 3
  alpha_t: 0.75
  mask_ratio: 0.75

DATA:
  data_folder: '/data1/share/SCN/zhangyc/SegOrganelle/Data/organelle_hist_match_500/hela'
  mam_folder: '/data1/share/SCN/zhangyc/SegOrganelle/Data/organelle_hist_match_500_sam/hela'


